# src/biointel/sources/patents.py
"""Patent layer: firm-technology substrate from Google Patents Public
Datasets on BigQuery (adopted route, PROJECT_STATUS v0.73).

`patents-sql` writes gold/patents_bigquery.sql with match.canon()
reproduced in SQL; the operator runs it in the BigQuery console and
drops the CSV export into data/bronze/patents_bulk/; `patents-import`
consumes that export into silver/patents.csv (IID, PatentId, dates,
CPCSubclass). The earlier PatentSearch API and USPTO bulk-download
routes are dead (v0.70-0.72) and were removed in refactor step 1.

JOIN. Assignee names match companies.csv Name/FDAAliases via
match.canon() exact equality, so failures are missing, never wrong.
"""

from __future__ import annotations

import csv
from datetime import date

from biointel import config, store
from biointel.match import canon

BULK_DIR = config.BRONZE / "patents_bulk"
PATENTS_TABLE = "patents"

# --------------------------------------------------------------------------
# BigQuery route (Google Patents Public Datasets) -- keyless for the
# operator beyond an existing Google login. `patents-sql` writes a query
# generated from the operator's own company names; the operator runs it
# in the BigQuery console and exports the result; `patents-import`
# consumes that export. Matching happens on a canon() key computed
# IDENTICALLY on both sides: Python emits the key list from match.canon,
# and the SQL reproduces canon (uppercase, punctuation to space, & to
# AND, strip the same legal-suffix/descriptor word list, collapse
# whitespace), so the round trip is deterministic and failures are
# missing, never wrong.
# --------------------------------------------------------------------------
SQL_OUT = config.EXPORTS / "patents_bigquery.sql"
EXPORT_COLS = [
    "publication_number",
    "assignee_name",
    "match_key",
    "filing_date",
    "grant_date",
    "cpc_subclass",
]


def _name_sources() -> list[tuple[str, str]]:
    """(name, IID-or-CIK-tag) pairs from companies.csv (+ aliases) and,
    when present, universe.csv."""
    out = []
    for r in store.read_table("companies"):
        if not r.get("IID"):
            continue
        out.append((r.get("Name", ""), r["IID"]))
        for a in (r.get("FDAAliases") or "").split(";"):
            if a.strip():
                out.append((a.strip(), r["IID"]))
    for r in store.read_table("universe"):
        if r.get("Name"):
            out.append((r["Name"], f"CIK:{r.get('CIK', '')}"))
    return out


def canon_key_map() -> dict[str, str]:
    """canon(name) -> tag. Tags are the company IID when known from
    companies.csv (aliases included); universe-only members carry a
    'CIK:<cik>' tag so expanded-universe firms are still captured.
    Deterministic rule: an IID always wins over a CIK tag; otherwise
    first-seen wins."""
    m: dict[str, str] = {}
    for name, tag in _name_sources():
        k = canon(name)
        if not k:
            continue
        if k not in m or (m[k].startswith("CIK:") and not tag.startswith("CIK:")):
            m[k] = tag
    return m


def write_sql() -> dict:
    """Generate gold/patents_bigquery.sql for the operator to paste into
    the BigQuery console (project bigquery-public-data is not needed;
    the table is patents-public-data.patents.publications)."""
    from biointel import match as _match

    keys = sorted(canon_key_map())
    if not keys:
        return {"status": "fail", "message": "No company names found (companies.csv empty?)."}
    strip_words = "|".join(sorted(_match.STRIP))
    key_list = ",\n    ".join(f"'{k}'" for k in keys)
    sql = f"""-- Generated by biointel patents-sql on {date.today().isoformat()}
-- Run in the BigQuery console (console.cloud.google.com/bigquery) while
-- signed in with your Google account. Then: Save results -> CSV
-- (Google Drive if over 10 MB), download it, place it in
-- data\\bronze\\patents_bulk\\ and run:  python -m biointel patents-import
WITH keys AS (
  SELECT k FROM UNNEST([
    {key_list}
  ]) AS k
),
pubs AS (
  SELECT p.publication_number,
         a.name AS assignee_name,
         TRIM(REGEXP_REPLACE(REGEXP_REPLACE(
             REGEXP_REPLACE(REGEXP_REPLACE(UPPER(a.name),
                 r"'", ''),
                 r'&', ' AND '),
                 r'[^A-Z0-9 ]', ' '),
             r'\\b({strip_words})\\b', ' ')) AS raw_key,
         p.filing_date, p.grant_date,
         c.code AS cpc_code
  FROM `patents-public-data.patents.publications` AS p,
       UNNEST(p.assignee_harmonized) AS a,
       UNNEST(p.cpc) AS c
  WHERE p.country_code = 'US' AND p.grant_date > 0
)
SELECT DISTINCT
  publication_number, assignee_name,
  REGEXP_REPLACE(raw_key, r' +', ' ') AS match_key,
  filing_date, grant_date,
  SUBSTR(cpc_code, 1, 4) AS cpc_subclass
FROM pubs
WHERE REGEXP_REPLACE(raw_key, r' +', ' ') IN (SELECT k FROM keys)
"""
    SQL_OUT.parent.mkdir(parents=True, exist_ok=True)
    SQL_OUT.write_text(sql, encoding="utf-8")
    return {
        "status": "ok",
        "message": f"SQL written for {len(keys)} name keys -> {SQL_OUT}\n"
        "Open console.cloud.google.com/bigquery (your normal "
        "Google login), paste the file contents, Run, then "
        "Save results -> CSV (Drive if over 10 MB), download, "
        "drop the .csv into data\\bronze\\patents_bulk\\ and "
        "run: python -m biointel patents-import",
    }


def _iso(d: str) -> str:
    d = (d or "").strip()
    return f"{d[0:4]}-{d[4:6]}-{d[6:8]}" if len(d) == 8 and d.isdigit() else ""


def import_export() -> dict:
    """Consume the BigQuery CSV export(s) from data/bronze/patents_bulk/
    into silver/patents.csv."""
    BULK_DIR.mkdir(parents=True, exist_ok=True)
    files = sorted(BULK_DIR.glob("*.csv"))
    if not files:
        return {
            "status": "fail",
            "message": "No .csv export found in data\\bronze\\"
            "patents_bulk\\. Run patents-sql, execute it in "
            "BigQuery, export, and drop the file there.",
        }
    kmap = canon_key_map()
    n_out, n_unmatched, firms = 0, 0, set()
    rows_out: list[dict] = []
    for path in files:
        with path.open(encoding="utf-8", newline="", errors="replace") as f:
            rd = csv.DictReader(f)
            missing = [c for c in EXPORT_COLS if c not in (rd.fieldnames or [])]
            if missing:
                return {
                    "status": "fail",
                    "message": f"HEADER MISMATCH in {path.name}: "
                    f"missing {missing}. REAL header -- "
                    "paste back so this is corrected:\n"
                    f"{rd.fieldnames}",
                }
            for r in rd:
                tag = kmap.get(r["match_key"])
                if not tag:
                    n_unmatched += 1
                    continue
                rows_out.append(
                    {
                        "IID": tag,
                        "PatentId": r["publication_number"],
                        "PatentDate": _iso(r["grant_date"]),
                        "FilingDate": _iso(r["filing_date"]),
                        "CPCSubclass": r["cpc_subclass"],
                        "AssigneeRaw": r["assignee_name"],
                    }
                )
                n_out += 1
                firms.add(tag)
    store.write_table(
        PATENTS_TABLE,
        rows_out,
        ["IID", "PatentId", "PatentDate", "FilingDate", "CPCSubclass", "AssigneeRaw"],
    )
    return {
        "status": "ok",
        "message": f"patents: {n_out:,} patent-CPC rows across "
        f"{len(firms)} matched keys "
        f"({n_unmatched:,} export rows with no local key -- "
        f"expected 0) -> table {PATENTS_TABLE}",
    }
